import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/loginclassic">LoginClassic</Link>
        </li>
        <li>
          <Link to="/loginmodern">LoginModern</Link>
        </li>
        <li>
          <Link to="/registerclassic">RegisterClassic</Link>
        </li>
        <li>
          <Link to="/registermodern">RegisterModern</Link>
        </li>
        <li>
          <Link to="/forgotpasswordclassic">ForgotPasswordClassic</Link>
        </li>
        <li>
          <Link to="/forgotpasswordmodern">ForgotPasswordModern</Link>
        </li>
        <li>
          <Link to="/newpasswordclassic">NewPasswordClassic</Link>
        </li>
        <li>
          <Link to="/newpasswordmodern">NewPasswordModern</Link>
        </li>
        <li>
          <Link to="/verifyclassic">VerifyClassic</Link>
        </li>
        <li>
          <Link to="/verifymodern">VerifyModern</Link>
        </li>
        <li>
          <Link to="/home1">Home1</Link>
        </li>
        <li>
          <Link to="/previewcomponents">PreviewComponents</Link>
        </li>
        <li>
          <Link to="/pricing">Pricing</Link>
        </li>
        <li>
          <Link to="/about">About</Link>
        </li>
        <li>
          <Link to="/contact">Contact</Link>
        </li>
        <li>
          <Link to="/faqs">FAQs</Link>
        </li>
        <li>
          <Link to="/error403">Error403</Link>
        </li>
        <li>
          <Link to="/error404">Error404</Link>
        </li>
        <li>
          <Link to="/error500">Error500</Link>
        </li>
        <li>
          <Link to="/payments">Payments</Link>
        </li>
        <li>
          <Link to="/paymentsnewcard">PaymentsNewCard</Link>
        </li>
        <li>
          <Link to="/maintenance">Maintenance</Link>
        </li>
        <li>
          <Link to="/comingsoon">ComingSoon</Link>
        </li>
        <li>
          <Link to="/app">App</Link>
        </li>
        <li>
          <Link to="/miniapp">MINIApp</Link>
        </li>
        <li>
          <Link to="/horizontalapp">HORIZONTALApp</Link>
        </li>
        <li>
          <Link to="/ecommerce">Ecommerce</Link>
        </li>
        <li>
          <Link to="/miniecommerce">MINIEcommerce</Link>
        </li>
        <li>
          <Link to="/horizontalecommerce">HORIZONTALEcommerce</Link>
        </li>
        <li>
          <Link to="/analytics">Analytics</Link>
        </li>
        <li>
          <Link to="/minianalytics">MINIAnalytics</Link>
        </li>
        <li>
          <Link to="/horizontalanalytics">HORIZONTALAnalytics</Link>
        </li>
        <li>
          <Link to="/banking">Banking</Link>
        </li>
        <li>
          <Link to="/minibanking">MINIBanking</Link>
        </li>
        <li>
          <Link to="/horizontalbanking">HORIZONTALBanking</Link>
        </li>
        <li>
          <Link to="/booking">Booking</Link>
        </li>
        <li>
          <Link to="/minibooking">MINIBooking</Link>
        </li>
        <li>
          <Link to="/horizontalbooking">HORIZONTALBooking</Link>
        </li>
        <li>
          <Link to="/file">File</Link>
        </li>
        <li>
          <Link to="/minifile">MINIFile</Link>
        </li>
        <li>
          <Link to="/horizontalfile">HORIZONTALFile</Link>
        </li>
        <li>
          <Link to="/userprofile">UserProfile</Link>
        </li>
        <li>
          <Link to="/useraccount">UserAccount</Link>
        </li>
        <li>
          <Link to="/productlist">ProductList</Link>
        </li>
        <li>
          <Link to="/producthomeshop">ProductHomeShop</Link>
        </li>
        <li>
          <Link to="/producthomeshopfilters">ProductHomeShopFilters</Link>
        </li>
        <li>
          <Link to="/productcheckoutcart">ProductCheckoutCart</Link>
        </li>
        <li>
          <Link to="/productcheckoutcartempty">ProductCheckoutCartEmpty</Link>
        </li>
        <li>
          <Link to="/orderlist">OrderList</Link>
        </li>
        <li>
          <Link to="/invoice">Invoice</Link>
        </li>
        <li>
          <Link to="/blogpostlist">BlogPostList</Link>
        </li>
        <li>
          <Link to="/blog">Blog</Link>
        </li>
        <li>
          <Link to="/joblist">JobList</Link>
        </li>
        <li>
          <Link to="/joblistfilters">JobListFilters</Link>
        </li>
        <li>
          <Link to="/tourlist">TourList</Link>
        </li>
        <li>
          <Link to="/tourlistfilters">TourListFilters</Link>
        </li>
        <li>
          <Link to="/filemanagerlist">FileManagerList</Link>
        </li>
        <li>
          <Link to="/mail">Mail</Link>
        </li>
        <li>
          <Link to="/chat">Chat</Link>
        </li>
        <li>
          <Link to="/calendar">Calendar</Link>
        </li>
        <li>
          <Link to="/calendarfilters">CalendarFilters</Link>
        </li>
        <li>
          <Link to="/kanban">Kanban</Link>
        </li>
        <li>
          <Link to="/kanbanscroll">KanbanScroll</Link>
        </li>
        <li>
          <Link to="/mailselected">MailSelected</Link>
        </li>
        <li>
          <Link to="/kanbantaskdetails">KanbanTaskDetails</Link>
        </li>
        <li>
          <Link to="/chatdetailssingle">ChatDetailsSingle</Link>
        </li>
        <li>
          <Link to="/chatdetailscollapsenav">ChatDetailsCollapseNav</Link>
        </li>
        <li>
          <Link to="/calendaraddeditevent">CalendarAddEditEvent</Link>
        </li>
        <li>
          <Link to="/productcheckoutaddress">ProductCheckoutAddress</Link>
        </li>
        <li>
          <Link to="/productcheckoutnewaddress">ProductCheckoutNewAddress</Link>
        </li>
        <li>
          <Link to="/productdetails">ProductDetails</Link>
        </li>
        <li>
          <Link to="/orderdetails">OrderDetails</Link>
        </li>
        <li>
          <Link to="/invoicedetails">InvoiceDetails</Link>
        </li>
        <li>
          <Link to="/filemanagergrid">FileManagerGrid</Link>
        </li>
        <li>
          <Link to="/tourdetails">TourDetails</Link>
        </li>
        <li>
          <Link to="/tourdetailsbooker">TourDetailsBooker</Link>
        </li>
        <li>
          <Link to="/useraccountbilling">UserAccountBilling</Link>
        </li>
        <li>
          <Link to="/useraccountbillingselectaddress">
            UserAccountBillingSelectAddress
          </Link>
        </li>
        <li>
          <Link to="/jobdetails">JobDetails</Link>
        </li>
        <li>
          <Link to="/jobdetailscandidates">JobDetailsCandidates</Link>
        </li>
        <li>
          <Link to="/blogpost">BlogPost</Link>
        </li>
        <li>
          <Link to="/producthomedetails">ProductHomeDetails</Link>
        </li>
        <li>
          <Link to="/blogpostdetails">BlogPostDetails</Link>
        </li>
        <li>
          <Link to="/mailnew">MailNew</Link>
        </li>
        <li>
          <Link to="/mailnewfullscreen">MailNewFullScreen</Link>
        </li>
        <li>
          <Link to="/chatdetailsgroup">ChatDetailsGroup</Link>
        </li>
        <li>
          <Link to="/useraccountbillingselectcard">
            UserAccountBillingSelectCard
          </Link>
        </li>
        <li>
          <Link to="/userprofilefollowers">UserProfileFollowers</Link>
        </li>
        <li>
          <Link to="/productcheckoutpayment">ProductCheckoutPayment</Link>
        </li>
        <li>
          <Link to="/productcheckoutpaymentnewcard">
            ProductCheckoutPaymentNewCard
          </Link>
        </li>
        <li>
          <Link to="/filemanagerdetails">FileManagerDetails</Link>
        </li>
        <li>
          <Link to="/invoicecreate">InvoiceCreate</Link>
        </li>
        <li>
          <Link to="/invoicecreateselectclient">InvoiceCreateSelectClient</Link>
        </li>
        <li>
          <Link to="/productnew">ProductNew</Link>
        </li>
        <li>
          <Link to="/mailempty">MailEmpty</Link>
        </li>
        <li>
          <Link to="/chatdetailsgroupuserinfo">ChatDetailsGroupUserInfo</Link>
        </li>
        <li>
          <Link to="/userprofilefriends">UserProfileFriends</Link>
        </li>
        <li>
          <Link to="/jobnew">JobNew</Link>
        </li>
        <li>
          <Link to="/blogpostnewpreview">BlogPostNewPreview</Link>
        </li>
        <li>
          <Link to="/blogpostnew">BlogPostNew</Link>
        </li>
        <li>
          <Link to="/tournew">TourNew</Link>
        </li>
        <li>
          <Link to="/useraccountnotifications">UserAccountNotifications</Link>
        </li>
        <li>
          <Link to="/productcheckoutcomplete">ProductCheckoutComplete</Link>
        </li>
        <li>
          <Link to="/userprofilegallery">UserProfileGallery</Link>
        </li>
        <li>
          <Link to="/useraccountsociallinks">UserAccountSocialLinks</Link>
        </li>
        <li>
          <Link to="/producthomedetailsreview">ProductHomeDetailsReview</Link>
        </li>
        <li>
          <Link to="/producthomedetailsnewreview">
            ProductHomeDetailsNewReview
          </Link>
        </li>
        <li>
          <Link to="/useraccountchangepassword">UserAccountChangePassword</Link>
        </li>
        <li>
          <Link to="/usercards">UserCards</Link>
        </li>
        <li>
          <Link to="/userlist">UserList</Link>
        </li>
        <li>
          <Link to="/userlistquickedit">UserListQuickEdit</Link>
        </li>
        <li>
          <Link to="/usercreate">UserCreate</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
